environment: production
http_port: 8080
grpc_port: 8889
auth_secret: ######

database_uri: root:Tungpro123@@tcp(127.0.0.1:3308)/e-commerce?parseTime=true

redis_uri: localhost:6379
redis_password:
redis_db: 0

SecretKey: Golang Course



